### PR TITLE
Insert git branching strategy inside README.md

### PR DESCRIPTION
**Pull request by JKnight44**
This is an example of merging into main

### CODE REVIEW

**Comment by ColinEller1** [comment]
Looks good to me. Do each of us need to click "Merge pull request" or just one of us?

**Comment by JKnight44** [comment]
@ColinEller1 Multiple people can approve it, but here i think we can go ahead an merge this in.

**Comment by dgib808** [comment]
Yes, this strategy works for me.

**Review by dgib808 — COMMENTED** [review]
This strategy looks good.

**Pull request merged**
